import type { Ficha } from '../types'

export function criarFichaInicial(): Ficha {
  return {
    identidade: {
      nome_personagem: null,
      nome_jogador: null,
      campanha: null,
      classe_id: null,
      subclasse_id: null,
      nivel: 1,
      multiclasses: [],
      especie_id: null,
      linhagem_id: null,
      antecedente_id: null,
      alinhamento: { etico: null, moral: null },
      idade: null, altura: null, peso: null, olhos: null, pele: null, cabelo: null,
      xp: 0,
    },
    atributos: {
      FOR: { valor: null, _modificador: null },
      DES: { valor: null, _modificador: null },
      CON: { valor: null, _modificador: null },
      INT: { valor: null, _modificador: null },
      SAB: { valor: null, _modificador: null },
      CAR: { valor: null, _modificador: null },
      metodo_geracao: null,
    },
    combate: {
      _bonus_proficiencia: null,
      pontos_de_vida: { maximo: null, atual: 0, temporario: 0 },
      dados_de_vida: { tipo: null, total: null, gastos: 0 },
      classe_de_armadura: { valor: null, origem: null, escudo_equipado: false, armadura_equipada_id: null },
      iniciativa: { _valor: null },
      deslocamento: { base_metros: null, bonus_metros: 0, _total_metros: null },
      ataques: [],
      salvaguardas: {
        FOR: { proficiente: false, _valor: null },
        DES: { proficiente: false, _valor: null },
        CON: { proficiente: false, _valor: null },
        INT: { proficiente: false, _valor: null },
        SAB: { proficiente: false, _valor: null },
        CAR: { proficiente: false, _valor: null },
      },
    },
    pericias: {
      acrobacia: { atributo: 'DES', proficiente: false, expertise: false, _valor: null },
      arcanismo: { atributo: 'INT', proficiente: false, expertise: false, _valor: null },
      atletismo: { atributo: 'FOR', proficiente: false, expertise: false, _valor: null },
      atuacao: { atributo: 'CAR', proficiente: false, expertise: false, _valor: null },
      enganacao: { atributo: 'CAR', proficiente: false, expertise: false, _valor: null },
      furtividade: { atributo: 'DES', proficiente: false, expertise: false, _valor: null },
      historia: { atributo: 'INT', proficiente: false, expertise: false, _valor: null },
      intimidacao: { atributo: 'CAR', proficiente: false, expertise: false, _valor: null },
      intuicao: { atributo: 'SAB', proficiente: false, expertise: false, _valor: null },
      investigacao: { atributo: 'INT', proficiente: false, expertise: false, _valor: null },
      lidar_com_animais: { atributo: 'SAB', proficiente: false, expertise: false, _valor: null },
      medicina: { atributo: 'SAB', proficiente: false, expertise: false, _valor: null },
      natureza: { atributo: 'INT', proficiente: false, expertise: false, _valor: null },
      percepcao: { atributo: 'SAB', proficiente: false, expertise: false, _valor: null },
      persuasao: { atributo: 'CAR', proficiente: false, expertise: false, _valor: null },
      prestidigitacao: { atributo: 'DES', proficiente: false, expertise: false, _valor: null },
      religiao: { atributo: 'INT', proficiente: false, expertise: false, _valor: null },
      sobrevivencia: { atributo: 'SAB', proficiente: false, expertise: false, _valor: null },
    },
    proficiencias: { armaduras: [], armas: [], ferramentas: [], idiomas: [] },
    tracos_de_especie: { visao_no_escuro_metros: null, tracos_ativos: [], escolhas_feitas: {} },
    caracteristicas_de_classe: {
      ativas: [],
      escolhas_feitas: {},
      recursos_de_classe: {
        furias: { maximo: null, atual: null },
        inspiracao_de_bardo: { dado: null, maximo: null, atual: null },
        canalizar_divindade: { maximo: null, atual: null },
        formas_selvagens: { maximo: null, atual: null },
        pontos_de_feiticaria: { maximo: null, atual: null },
        imposicao_de_maos: { pool_pv: null, atual: null },
        pontos_de_foco: { maximo: null, atual: null },
        surto_de_acao: { usos: null, atual: null },
        recuperar_folego: { maximo: null, atual: null },
        ataque_furtivo: { dado: null },
        recuperacao_arcana: { circulos_recuperaveis: null },
      },
      ordem_divina: null,
      estilo_de_luta: null,
      juramento: null,
    },
    magia: {
      conjurador: false,
      atributo_conjuracao: null,
      _cd_magia: null,
      _bonus_ataque_magia: null,
      truques_conhecidos: [],
      magias_preparadas: [],
      livro_de_magias: [],
      espacos_de_magia: {
        c1: { maximo: 0, gastos: 0 }, c2: { maximo: 0, gastos: 0 }, c3: { maximo: 0, gastos: 0 },
        c4: { maximo: 0, gastos: 0 }, c5: { maximo: 0, gastos: 0 }, c6: { maximo: 0, gastos: 0 },
        c7: { maximo: 0, gastos: 0 }, c8: { maximo: 0, gastos: 0 }, c9: { maximo: 0, gastos: 0 },
      },
      espacos_pacto_bruxo: { circulo: null, maximo: 0, gastos: 0 },
    },
    inventario: {
      moedas: { PC: 0, PP: 0, PE: 0, PO: 0, PL: 0 },
      itens: [],
    },
    talentos: { lista: [] },
    personalidade: {
      tracos: [], ideais: [], vinculos: [], fraquezas: [],
      historia: null, aparencia_descricao: null, aliados_e_organizacoes: null, simbolo_ou_tesouro: null,
    },
    condicoes_ativas: [],
    niveis_de_exaustao: 0,
    notas: null,
  }
}
