import type { CharacterSheet } from '../types'

export function createInitialSheet(): CharacterSheet {
  return {
    identity: {
      character_name: null,
      player_name: null,
      campaign: null,
      class_id: null,
      subclass_id: null,
      level: 1,
      multiclasses: [],
      species_id: null,
      lineage_id: null,
      background_id: null,
      background_distribution: {},
      equipment_option: null,
      alignment: { ethical: null, moral: null },
      age: null, height: null, weight: null, eyes: null, skin: null, hair: null,
      xp: 0,
    },
    abilities: {
      FOR: { value: null, _modifier: null },
      DES: { value: null, _modifier: null },
      CON: { value: null, _modifier: null },
      INT: { value: null, _modifier: null },
      SAB: { value: null, _modifier: null },
      CAR: { value: null, _modifier: null },
      generation_method: null,
    },
    combat: {
      _proficiency_bonus: null,
      hit_points: { max: null, current: 0, temporary: 0 },
      hit_dice: { type: null, total: null, spent: 0 },
      armor_class: { value: null, source: null, shield_equipped: false, equipped_armor_id: null },
      initiative: { _value: null },
      speed: { base_meters: null, bonus_meters: 0, _total_meters: null },
      attacks: [],
      saves: {
        FOR: { proficient: false, _value: null },
        DES: { proficient: false, _value: null },
        CON: { proficient: false, _value: null },
        INT: { proficient: false, _value: null },
        SAB: { proficient: false, _value: null },
        CAR: { proficient: false, _value: null },
      },
    },
    skills: {
      acrobacia: { ability: 'DES', proficient: false, expertise: false, _value: null },
      arcanismo: { ability: 'INT', proficient: false, expertise: false, _value: null },
      atletismo: { ability: 'FOR', proficient: false, expertise: false, _value: null },
      atuacao: { ability: 'CAR', proficient: false, expertise: false, _value: null },
      enganacao: { ability: 'CAR', proficient: false, expertise: false, _value: null },
      furtividade: { ability: 'DES', proficient: false, expertise: false, _value: null },
      historia: { ability: 'INT', proficient: false, expertise: false, _value: null },
      intimidacao: { ability: 'CAR', proficient: false, expertise: false, _value: null },
      intuicao: { ability: 'SAB', proficient: false, expertise: false, _value: null },
      investigacao: { ability: 'INT', proficient: false, expertise: false, _value: null },
      lidar_com_animais: { ability: 'SAB', proficient: false, expertise: false, _value: null },
      medicina: { ability: 'SAB', proficient: false, expertise: false, _value: null },
      natureza: { ability: 'INT', proficient: false, expertise: false, _value: null },
      percepcao: { ability: 'SAB', proficient: false, expertise: false, _value: null },
      persuasao: { ability: 'CAR', proficient: false, expertise: false, _value: null },
      prestidigitacao: { ability: 'DES', proficient: false, expertise: false, _value: null },
      religiao: { ability: 'INT', proficient: false, expertise: false, _value: null },
      sobrevivencia: { ability: 'SAB', proficient: false, expertise: false, _value: null },
    },
    proficiencies: { armors: [], weapons: [], tools: [], languages: [] },
    species_traits: { darkvision_meters: null, active_traits: [], choices_made: {} },
    class_features: {
      active: [],
      choices_made: {},
      class_resources: {
        rages: { max: null, current: null },
        bardic_inspiration: { die: null, max: null, current: null },
        channel_divinity: { max: null, current: null },
        wild_shapes: { max: null, current: null },
        sorcery_points: { max: null, current: null },
        lay_on_hands: { hp_pool: null, current: null },
        focus_points: { max: null, current: null },
        action_surge: { uses: null, current: null },
        second_wind: { max: null, current: null },
        sneak_attack: { die: null },
        arcane_recovery: { recoverable_slot_levels: null },
      },
      divine_order: null,
      primal_order: null,
      fighting_style: null,
      favored_enemy: null,
      oath: null,
    },
    spellcasting: {
      spellcaster: false,
      spellcasting_ability: null,
      _spell_dc: null,
      _spell_attack_bonus: null,
      _spell_dc_by_class: {},
      _spell_attack_by_class: {},
      cantrips_by_class: {},
      spells_by_class: {},
      spellbook: [],
      spell_slots: {
        c1: { max: 0, spent: 0 }, c2: { max: 0, spent: 0 }, c3: { max: 0, spent: 0 },
        c4: { max: 0, spent: 0 }, c5: { max: 0, spent: 0 }, c6: { max: 0, spent: 0 },
        c7: { max: 0, spent: 0 }, c8: { max: 0, spent: 0 }, c9: { max: 0, spent: 0 },
      },
      pact_slots: { level: null, max: 0, spent: 0 },
      free_casts: [],
    },
    inventory: {
      coins: { PC: 0, PP: 0, PE: 0, PO: 0, PL: 0 },
      items: [],
    },
    feats: { list: [] },
    personality: {
      traits: [], ideals: [], bonds: [], flaws: [],
      backstory: null, appearance_description: null, allies_and_organizations: null, symbol_or_treasure: null,
    },
    active_conditions: [],
    exhaustion_levels: 0,
    notes: null,
  }
}
